services:
  - type: web
    name: tts-api
    runtime: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    envVars:
      - key: LD_LIBRARY_PATH
        value: /app/piper_total/piper:$LD_LIBRARY_PATH